Adding CRUD operations & exceptions
wolox-training/aa-java pull request #6
Opened 2022-07-21 15:05 UTC by AguirreAlexa

## Summary
- Adding CRUD operations into BookController.
- Creating custom exceptions for each method.
## Trello Card
https://trello.com/c/EJonZS6T/18-crear-las-operaciones-crud-de-book

2022-07-22 16:32 UTC, Jimenarosello requested changes
Great work!! Just one comment from my part and it should be good to go 😄

2022-07-22 16:32 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/BookController.java
> +    @GetMapping("/identify/{id}")
The RESTful path would be /{id}, without the `identify` part  😄  
GET: /books/ -> find all books
GET: /books/{id} -> find one book
POST: /books/ -> create one book
PUT / PATCH: /books/{id} -> modify one book
DELETE: /books/{id} -> delete one book

2022-07-22 20:08 UTC, AguirreAlexa commented on src/main/java/wolox/training/controllers/BookController.java
> +    @GetMapping("/identify/{id}")
Great, I thought I needed to differentiate between the search by Id and the search by tittle. Thanks!

2022-08-02 15:47 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/BookController.java
> +    @GetMapping("/identify/{id}")
oh!! the find by title could be something like "/title/{title}" to differentiate, that's my bad 😅 
If the path is the same, it will cause problems

2022-08-02 15:48 UTC, Jimenarosello approved these changes

2022-08-02 19:13 UTC, merged